config/routes.rb
Rails.application.routes.draw do

  get "vaga/nova" => "jobs#new", as: "new_job"
  post "vaga/nova" => "jobs#create", as: nil

  get "vaga/:id" => "jobs#show", as: "job"

  get "sobre" => "jobs#about", as: "about_job"

  root "jobs#index"

  post "jobs" => "newsletter#create"

  get "jobs" => "jobs#index", path: "vagas"

  # resources :jobs
  # resources :newsletters

end

app/models/job.rb
class Job < ActiveRecord::Base

	validates :title, presence: true
  validates :company, presence: true
  validates :description, presence: true
  # validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/ }
  # include PgSearch
  extend FriendlyId

  # pg_search_scope :search_everywhere, :against => [:title, :company], :ignoring => :accents

  
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [:title, :created_at]
  end

  def self.garbage_collector
    JobsCleanupJob.perform_later(Job.first(50))
  end

  #Implementar Full Text Search na versão 2.0
  def self.search(query)
    where("lower(title) like ?", "%#{query.downcase}%") 
  end

  private

  def upper
    "#{self.title.upcase}"
  end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	validates :email, presence: true#, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/ }

	def self.sender
		@jobs = Job.last(5)
		@emails = Newsletter.all.pluck(:email)
		SendEmailJob.perform_later(@emails, @jobs)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  # before_action :set_params, only: []

  def index
    @newsletter = Newsletter.new

    respond_to do |format|      
      if params[:search]
      
        @jobs = Job.page.search(params[:search]).per(10)
        format.html
        format.js {}
      else
        @jobs = Job.page(params[:page]).per(5).order("created_at DESC")
        format.html
        format.js          
      end  
    end
  end

  def new
  	@job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Vaga Anunciada com Sucesso!"
      redirect_to @job
    else
      flash[:alert] = "Erro ao cadastrar a vaga!"
      render :new
    end
  end

  def show
    @job = Job.friendly.find(params[:id])
  end

  def about
  end

  private

  def job_params
  	params.require(:job).permit(:title, :company, :url, :description, :slug, :email, :telephone)
  end
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController

  def create

  	@newsletter = Newsletter.new(newsletrer_params)
  	if @newsletter.save!     
  	  flash[:notice] = "Obrigado por se cadastrar em nossa newsletter!"  	  
      redirect_to root_path
  	else
  		flash[:alert] = "Erro ao cadastrar email em nossa newsletter."
      redirect_to root_path
  	end
  end

  private 

  def newsletrer_params
    params.require(:newsletter).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/time_helper.rb
module TimeHelper
  def timeago(time, options = {})
    options[:class] ||= "timeago"
    content_tag(
      :time,
      time.to_s,
      options.merge(datetime: time.getutc.iso8601)
    ) if time
  end
end

app/views/advertisements/_right_column.html.erb
Anúncios marotos :)

app/views/jobs/_job.html.erb
<% @jobs.each do |job| %>
  <div class="post-preview">
    <h2 class="post-title">
      <%= link_to job.title, job %>
    </h2>
    <h3 class="post-subtitle">
      <%= link_to job.company, job.url %>
    </h3>
                   
    <p class="post-meta">Vaga postada: <%= timeago(job.created_at)%></p>
      <%= link_to "Saiba mais.", job %>
  </div>
  <hr>
<% end %>

<ul class="pager">
  <li class="next">
     <%= paginate @jobs, data: { class: "pagination" } %>
  </li>
</ul>
<script>
$(function() {
  $("time.timeago").timeago();
});
</script>

app/views/jobs/about.html.erb
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="breadcumbs">
                  <i><%= link_to("Início/", root_path) %>Sobre o projeto</i>
                </div>
                <p>O Empregos Caldas Novas nasceu da ideia de facilitar a centralização e disponilibidade de vagas de empregos em Caldas Novas.</p>
                <p>O projeto ainda em fase beta é de cunho colaborativo, portanto não nos responsabilizamos pelo conteúdo das vagas aqui postadas.</p>
                <p>Esperamos que seja de grande benefício para futuros empregados e empregadores, a equipe CodeBeMine / CodeBeMe agradece pelo uso do software!</p>
                <p>
                    Desenvolvedores:
                    <ul>
                        <li><a href="https://github.com/felipecabral26">Felipe Cabral - Front-end Developer</a></li>
                        <li><a href="https://github.com/ocsjwolf">Osvaldo Carlos - Back-end Developer</a></li>
                        <li><a href="https://github.com/taikio">Welker Arantes - Mobile Developer</a></li>
                    </ul>
                </p>
                <br/>
                <%= link_to "Voltar ao início", root_path %>
            </div>
        </div>
    </div>

app/views/jobs/index.html.erb
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            	<%= form_tag(root_path, remote: true, method: "get", id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Pesquisar Vagas" %>
                  <%= submit_tag "pesquisar", :title => nil, class: "btn btn-info", data: { disable_with: "Pesquisando..." } %>
            	    
                <% end %>
                <div id="jobs">
                  <%= render "job" %>
                </div>
                <div class=" col-md-4">
                  <%= link_to("Anuncie sua Vaga", new_job_path, class: "btn btn-success") %>
                </div>
                <div class=" col-md-8">
                  <%= render "newsletters/create" %>
                </div>
            </div>
        </div>
    </div>

app/views/jobs/index.js.erb
-$('#jobs').html("<%= j (render 'job') %>");

app/views/jobs/new.html.erb
    <%= simple_form_for @job, url: { controller: "jobs", action: "create" } do |form| %>
      <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="breadcumbs">
                <i><%= link_to("Início/", root_path) %>Vaga Nova</i>
              </div>
                <% if flash[:alert] %>
                  <div class="alert alert-danger" role="alert"><%= flash[:alert] %>

                    <%#= form.error_notification %>
                    
                    <br/>
                  </div>
                <% end %>
                <form name="sentMessage" id="contactForm" novalidate>
                    
                  <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                      <%= form.input :title, placeholder: "Título da Vaga", class: "form-control", :input_html => {:maxlength => 180, :size => '100%'}%>
                      </div>
                  </div>
                  <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                      <%= form.input :company, label: "Nome da companhia", placeholder: "Nome da Companhia", class: "form-control", :input_html => {:maxlength => 180, :size => '100%'}%>
                      </div>
                  </div>
                  <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls"><%= form.input :url, label: "Link para vaga", placeholder: "Link da vaga ou site da empresa", class: "form-control", :input_html => {:maxlength => 180, :size => '100%'}, as: :url, required: false %>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls"><%= form.input :email, label: "Email:", placeholder: "Email de contato", class: "form-control", :input_html => {:maxlength => 180, :size => '100%'}, as: :email, required: false %>
                        </div>
                    </div>
                    
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls"><%= form.input :telephone, label: "Telefone:", placeholder: "Telefone de contato", class: "form-control", :input_html => {:maxlength => 180, :size => '100%'}, as: :tel, required: false %>
                        </div>
                    </div>

                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <%= form.input html_escape(:description), label: "Descrição da vaga", placeholder: "Descrição da Vaga", class: "form-control pre code", :input_html => { :rows => '5%', :cols => '100%' }  %>

                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                             <%= form.button :submit, "Anunciar", class: "btn btn-success", data: { disable_with: "Anunciando..." }%>
                        </div>
                    </div>
                </form>
                <% end %>
                    <%= link_to "Voltar ao início", root_path %>
            </div>
        </div>
    </div>

    <hr>

app/views/jobs/search.html.erb
Vagas buscadas

app/views/jobs/show.html.erb
<% content_for :opengraph do %>
  <%= tag("meta", property: "og:title", content: @job.title ) %>
  <%= tag("meta", property: "og:description", content: @job.description ) %>
  <%= tag("meta", property: "og:url", content: job_url(@job) ) %>
  <%= tag("meta", property: "og:image", content: asset_url('home-bg.jpg') ) %>
  <%= tag("meta", property: "og:site_name", content: "Empregos Caldas Novas" ) %>
<% end %>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="breadcumbs">
      <i><%= link_to("Início/", root_path) %>Vaga</i>
    </div>
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %>
        </div>
      <% end %>
      <br/>
      <br/>

      <h2>
        <strong>Vaga</strong> <%= link_to @job.title , @job.url %>
      </h2>
  
      <p>
        <strong>Companhia:</strong>
        <%= link_to @job.company, @job.url %>
      </p>

      <p>
        <strong>Email</strong>
        <%= mail_to(@job.email) %>
      </p>
      <p>
        <strong>Telefone</strong>
        <%= @job.telephone %>
      </p>

      <p>
        <strong>Descrição:</strong>
          <div class="line-box">
            <%= simple_format(h @job.description)%>
          </div>
      </p>

      <p>
      	<strong>Vaga postada:</strong>
      	<%= timeago(@job.created_at) %>
      </p>
      <br>
      <br>
        <%= link_to "Voltar ao início", root_path %>
        <%= link_to("Postar outra vaga?", new_job_path , class: "btn btn-success") %>
         <br>
      
      Compartilhar vaga: 
      <%= render_shareable :static_link => true, :buttons => ['twitter', 'facebook', 'linkedin'] %>
      

  </div>
</div>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55ae3dc17c6e5f91" async="async"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empregos Caldas Novas! O que você quer, onde você quer.</title>
  <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true, :view_port => "true" %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="Empregos Caldas Novas, empregos, trabalhos, vagas, vagas de emprego, caldas novas, goiás, oportunidade de emprego, oportunidade de trabalho, emprego em caldas novas">
  <meta name="author" content="CodeBeMe, agência de desenvolvimento web">  

   <%= yield :opengraph %>

</head>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to "Início", root_path %>
                    </li>
                    <li>
                      <%= link_to "Sobre o Empregos Caldas Novas",about_job_path %>
                    </li>

                    <li>
                    	<%= link_to("Anuncie sua Vaga", new_job_path, class: "btn btn-success") %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

     <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
  <%= link_to root_path do %>
    <header class="intro-header" style="background-image: url(<%= asset_path('home-bg.jpg')%>)">
        <%#= image_tag("home-bg.jpg", class: "intro-home") %>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Empregos Caldas Novas!</h1>
                        <hr class="small">
                        <span class="subheading">O que você quer, onde você quer.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <% end %>


<%= yield %>

<%#= render "advertisements/right_column" %>

 <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                      <ul class="list-inline text-center">
                        <!-- <li>
                            <a href="https://twitter.com/codebeme", target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="http://facebook.com/CodeBeMine", target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li> -->
                      </ul>
                    <p class="copyright text-muted">
                    	<a href="http://codebe.me", target="_blank">CodeBeMe | Agência de Desenvolvimento Web</a>
                    	<br/> 
                    	Copyright &copy;<%= Time.now.year %></p>
                </div>
            </div>
        </div>
    </footer>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/newsletters/_create.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %>
  </div>
<% end %>
<%= form_for @newsletter, url: { controller: "newsletter", action: "create" } do |form| %>
  Assine nossa newsletter:
  
  <%= form.email_field :email, required: true, placeholder: "Seu email aqui" %>
  <%= form.submit "Assinar", class: "btn btn-primary", required: true, data: { disable_with: "Assinando..." } %>

<% end %>

app/views/sender_newsletter/send_newsletter.html.erb
  	Algumas vagas recentes:
    <% @jobs.each do |job|%>
    <tr>
    	<td>
    		<%= link_to job.title, job %>
    	</td>
    	<td>
    	  <%= link_to job.company, job.url %>
    	</td>
    	<td>
    		<%= job.description  %>
    	</td>
    </tr>
    <% end %>
  

app/views/shareable/_facebook.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://www.facebook.com/sharer.php?u=#{options[:url]}") %>
  <% end %>
<% else %>
<div id="fb-root"></div>
  <% if !options[:button_only] && !options[:turbolinks] %>
    <%= output_once :facebook do %>
      <%= render "shareable/partials/scripts/facebook", :app_id => options[:app_id] %>
    <% end %>
  <% end %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<div class="fb-like" data-href='<%= options[:url] %>'
     data-send='<%= options[:send] %>'
     data-layout='<%= options[:layout] %>'
     data-show-faces='<%= options[:show_faces] %>'
     data-width='<%= options[:width] %>'
     data-action='<%= options[:action] %>'
     data-font='<%= options[:font] %>'
     data-colorscheme='<%= options[:colorscheme] %>'
     data-ref='<%= options[:ref] %>'
     data-share='<%= options[:share] %>'
     data-kid-directed-site='<%= options[:kid_directed_site] %>' >
</div>
  <% end %>
  <% if options[:turbolinks] && !options[:button_only] %>
    <%= output_once :facebook do %>
<script>
  if (typeof window.facebookLoaded == 'undefined') {
    var facebookLoaded = false;
  }
  var __loadFacebook = function() {
    if (facebookLoaded !== true) {
      $('head').append("<script><%= raw(render 'shareable/partials/scripts/head/facebook', :app_id=>options[:app_id]) %><\/script>");
    }
  };
  if (typeof $.turbo == 'undefined') {
    $(function() {
      return __loadFacebook();
    });
  }
  //for jquery.turbolinks
  else {
    __loadFacebook();  
  }
</script>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_google_plus.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://plus.google.com/share?url=#{options[:url]}") %>
  <% end %>
<% else %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<div class="g-plusone gplusshare"
  <%= html_attributes(options.slice(:url, :size, :annotation, :width, :align, :expand_to, :callback, :onstartinteraction, :onendinteraction, :recommendations), :data => true) %>
></div>
  <% end %>
  <% unless options[:button_only] %>
    <%= output_once :google_plus do %>
      <%= render "shareable/partials/scripts/google_plus" %>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_linkedin.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://www.linkedin.com/shareArticle?url=#{options[:url]}&title=#{options[:title]}&summary=#{options[:description]}") %>
  <% end %>
<% else %>
  <% if !options[:button_only] && !options[:turbolinks] %>
    <%= output_once :linkedin do %>
      <%= render "shareable/partials/scripts/linkedin" %>
    <% end %> 
  <% end %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<script type="IN/Share"
  <%= html_attributes(options.slice(:url, :counter, :onerror, :onsuccess, :showzero), :data => true) %>
></script>
  <% end %>
  <% if options[:turbolinks] && !options[:button_only] %>
    <%= output_once :linkedin do %>
<script type="text/javascript">
  if (typeof window.linkedinLoaded == 'undefined') {
    var linkedinLoaded = false;
  }
  var __loadLinkedin = function() {
    if (linkedinLoaded !== true) {
      $('head').append("<script><%= raw(render 'shareable/partials/scripts/head/linkedin') %><\/script>");
    }
  };
  if (typeof $.turbo == 'undefined') {
    $(function() {
      return __loadLinkedin();
    });
  }
  //for jquery.turbolinks
  else {
    if (linkedinLoaded !== true) {
    __loadLinkedin();  
    }
  }
</script>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_pinterest.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://pinterest.com/pin/create/button/?url=#{options[:url]}&description=#{options[:description]}&media=#{options[:media]}") %>
  <% end %>
<% else %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<a data-pin-config="<%= options[:pin_config] %>"
   href="//pinterest.com/pin/create/button/?url=<%= options[:url] %><%= raw('&media=' + options[:media]) unless options[:media].blank? %><%= raw('&description=' + options[:description]) unless options[:description].blank? %>"
   data-pin-do="<%= options[:pin_do] %>" data-pin-shape="<%= options[:pin_shape] %>" data-pin-height="<%= options[:pin_height] %>" data-pin-color="<%= options[:pin_color] %>" >
  <img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" title="<%= options[:title]%>" alt="<%= options[:alt] %>" /></a>
  <% end %>
  <% unless options[:button_only] %>
    <%= output_once :pinterest do %>
      <% if options[:turbolinks] %>
<script>
  var Pinterest;
  Pinterest = {
    load: function() {
      delete window["PIN_" + ~~((new Date).getTime() / 864e5)];
      return $.getScript("//assets.pinterest.com/js/pinit.js");
    }
  };
  $(function() {
    return Pinterest.load();
  });
  $(document).on('page:load', function() {
    return Pinterest.load();
  });
</script>
      <% else %>
        <%= render "shareable/partials/scripts/pinterest" %> 
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_reddit.html.erb
<%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
  <% if options[:static_link] %>
  <%= render "shareable/partials/link", :options => options.merge(:url=>"https://ssl.reddit.com/submit?url=#{options[:url]}&title=#{options[:title]}") %>
  <% else %>
    <% if !options[:turbolinks] %>
<script type="text/javascript">
    reddit_url='<%= options[:url] %>';
    reddit_target='<%= options[:target]%>';
    reddit_title='<%= options[:title] %>';
    reddit_bgcolor='<%= options[:color] %>';
    reddit_bordercolor='<%= options[:bordercolor] %>';
    reddit_newwindow='<%= options[:newwindow] %>';
</script>
      <% unless options[:button_only] %>
<script type="text/javascript"
src="<%= raw(options[:btnsrc].blank? ? ('//www.reddit.com/static/button/button' + options[:type] + '.js') : ('//www.reddit.com/buttonlite.js?i=' + options[:points] + '&styled=' + options[:styled])) %>">
</script>
      <% end %>
    <% else #if turbolinks is enabled then use this iframe hack %>
    <%# TODO: move to reddit tag class %>
      <% unless options[:type].blank? || options[:button_only] %>
        <% width, height = case options[:type] %>
         <% when '1' then ['120', '22'] %>
         <% when '2' then ['51', '69'] %>
         <% when '3' then ['69', '52'] %>
         <% else ['0', '0'] %>
        <% end %>
<iframe src="//www.reddit.com/static/button/button<%= options[:type] %>.html?width=<%= width %>&url=<%= url_encode(options[:url]) %>&target=<%= options[:target]%>&title=<%= url_encode(options[:title]) %>&bgcolor=<%= options[:color] %>&bordercolor=<%= options[:bordercolor] %>&newwindow=<%= options[:newwindow] %>" height="<%= height %>" width="<%= width %>" scrolling="no" frameborder="0"></iframe>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_social_buttons.html.erb
<%= render :layout =>'shareable/partials/parent_wrapper' do %>
  <%= social_buttons.render do %>
    <% each_button do |button| %>
      <%= eval button + '_tag' %>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_stumble_upon.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://www.stumbleupon.com/submit?url=#{options[:url]}&title=#{options[:title]}") %>
  <% end %>
<% else %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<su:badge layout="<%= options[:badge_layout]%>" location="<%= options[:url] %>"></su:badge>
  <% end %>
  <% unless options[:button_only] %>
    <%= output_once :stumble_upon do %>
      <%= render "shareable/partials/scripts/stumble_upon" %> 
    <% end %>
  <% end %>
<% end %>

app/views/shareable/_tumblr.html.erb
<% if options[:static_link] %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
    <%= render "shareable/partials/link", :options => options.merge(:url=>"https://www.tumblr.com/share/link?url=#{options[:url]}&name=#{options[:title]}&description=#{options[:description]}") %>
  <% end %>
<% else %>
  <%= render :layout => "shareable/partials/button_wrapper", locals: {:options => options} do %>
<a href="https://www.tumblr.com/share/link?url=<%= options[:url] %>&name=<%= options[:title] %>&description=<%= options[:description] %>" title="Share on Tumblr" 
style="display:inline-block; text-indent:-9999px; overflow:hidden; width:<%= options[:width] %>px; height:20px; background:url('https://platform.tumblr.com/v1/share_<%= options[:background] %>.png') top left no-repeat transparent; vertical-align:top;" class="tumblr-button">Share on Tumblr</a>
  <% end %>
  <% unless options[:button_only] %>
    <%= output_once :tumblr do %>
      <%= render "shareable/partials/scripts/tumblr" %>
    <% end %>
  <% end %>
<% end %>

app/views/shareable/partials/_button_wrapper.html.erb
<%= yield %>

app/views/shareable/partials/_link.html.erb
<a target="_blank" href="<%= options[:url] %>"><%= options[:button_caption] %></a>

app/views/shareable/partials/_parent_wrapper.html.erb
<nav class="share">
 <%= yield %>
</nav>

app/views/shareable/partials/scripts/_facebook.html.erb
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1<%= raw('&appId=' + app_id.to_s) if defined?(app_id) %>&status=0&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>